### ISSUE TITLE
How to modify demo.yaml to run demo_video.py

### ISSUE THREAD

**Issue by ffiioonnaa** [bytedance/Shot2Story#12]
Hi, thanks for your work!
I want to test my own videos, but I got this error when I run  demo_video.py:
FileNotFoundError: [Errno 2] No such file or directory: '/export/home/.cache/lavis/annotations/20k_train.json'
Can you tell me how to do then?
In addition, I would like to ask witch tasks are provided in this demo_video.py

**Comment by youthHan** [comment]
Hi you can have a try with our [online demo](https://huggingface.co/spaces/mhan/Shot2Story).

The `demo_video.py` provides the chatbot using generated video summaries. For starting the demo locally, you need to set some folders, in the same approach to prepare for training.
```bash
S2S_DIR="YOUR_S2S_DIR"
cd $S2S_DIR/code

#get data
sudo mkdir -p /export/home/.cache/
sudo chmod a+w /export/home/.cache
cd /export/home/.cache/
ln -s ${S2S_DIR}/data lavis
cd -
```

This will set the folders required by the code initialization.

**Comment by youthHan** [comment]
Hi I will close this issue due to long-time inactivity. Please feel free to open if you still have questions.
