### ISSUE TITLE
Unable to setup the environment from the yml file

### ISSUE THREAD

**Issue by rrss-01** [bytedance/Shot2Story#13]
I want to use this for inferencing on custom videos.

I initially tried to setup the environment using conda env create -f conda_env.yml which led to a conflict between dependencies due to the python --version being 3.8 in the yml file. Later I have looked in the previous issues and used temp branch

Collecting einops==0.7.0 (from -r /home/***/Shot2Story/code/condaenv.mya5kw6u.requirements.txt (line 49))
  Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
 
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9; 2.0.0a0 Requires-Python <3.12,>=3.9; 2.0.0rc1 Requires-Python <=3.12,>=3.9; 2.2.0a2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement en-core-web-sm==3.0.0 (from versions: none)
ERROR: No matching distribution found for en-core-web-sm==3.0.0
 
[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: pip install --upgrade pip
 
failed
 
CondaEnvException: Pip failed

after this i simply removed en-core-web-sm==3.0 from the yaml, then following happened

Collecting iopath==0.1.9 (from -r /home/***/Shot2Story/code/condaenv.xotr85xh.requirements.txt (line 87))

  Using cached iopath-0.1.9-py3-none-any.whl.metadata (370 bytes)
 
Pip subprocess error:

ERROR: Ignored the following yanked versions: 7.1.0, 7.30.0, 8.13.0

ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9; 2.0.0a0 Requires-Python <3.12,>=3.9; 2.0.0rc1 Requires-Python <=3.12,>=3.9; 2.2.0a2 Requires-Python >=3.9; 8.13.1 Requires-Python >=3.9; 8.13.2 Requires-Python >=3.9; 8.14.0 Requires-Python >=3.9; 8.15.0 Requires-Python >=3.9; 8.16.0 Requires-Python >=3.9; 8.16.1 Requires-Python >=3.9; 8.17.0 Requires-Python >=3.9; 8.17.1 Requires-Python >=3.9; 8.17.2 Requires-Python >=3.9; 8.18.0 Requires-Python >=3.9; 8.18.1 Requires-Python >=3.9; 8.19.0 Requires-Python >=3.10; 8.20.0 Requires-Python >=3.10; 8.21.0 Requires-Python >=3.10; 8.22.0 Requires-Python >=3.10; 8.22.1 Requires-Python >=3.10; 8.22.2 Requires-Python >=3.10; 8.23.0 Requires-Python >=3.10; 8.24.0 Requires-Python >=3.10; 8.25.0 Requires-Python >=3.10; 8.26.0 Requires-Python >=3.10

ERROR: Could not find a version that satisfies the requirement ipython==8.14.0 (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1, 7.16.2, 7.16.3, 7.17.0, 7.18.0, 7.18.1, 7.19.0, 7.20.0, 7.21.0, 7.22.0, 7.23.0, 7.23.1, 7.24.0, 7.24.1, 7.25.0, 7.26.0, 7.27.0, 7.28.0, 7.29.0, 7.30.1, 7.31.0, 7.31.1, 7.32.0, 7.33.0, 7.34.0, 8.0.0a1, 8.0.0b1, 8.0.0rc1, 8.0.0, 8.0.1, 8.1.0, 8.1.1, 8.2.0, 8.3.0, 8.4.0, 8.5.0, 8.6.0, 8.7.0, 8.8.0, 8.9.0, 8.10.0, 8.11.0, 8.12.0, 8.12.1, 8.12.2, 8.12.3)

ERROR: No matching distribution found for ipython==8.14.0
 
[notice] A new release of pip is available: 24.0 -> 24.1.1

[notice] To update, run: pip install --upgrade pip
 
failed
 
CondaEnvException: Pip failed

 

after that i decided to create a conda env with python=3.9 and tried to install the requirements from a txt file removing versions for every library which causes smart-open package to raise further conflicts . 

tried pip install for the same, again there were dependencies conflicts.

Any help will be appreciated for setting up the environment.

**Comment by youthHan** [comment]
Hi @rrss-01 sorry for this late reply. I have read through your provided logs. Do you know if the current env can run the code?

**Comment by rrss-01** [comment]
Hi @youthHan, Thankyou for the reply
yes it seems to be running demo_video.py
After these errors, I just ran the script and wherever import errors were coming, pip installed those.

Could you please tell me which directory needs to be specified in the below pair?

llama_model: "YOUR_VICUNA_7B_DIR" (from code/lavis/projects/blip2/eval/demo.yaml)

**Comment by youthHan** [comment]
Hi, good to hear that. The llama_model is the directory where you store the
Vicuna 7B v0 weights.
