### ISSUE TITLE
Erroneous data in 90k_gptv_train.json

### ISSUE THREAD

**Issue by yellow-binary-tree** [bytedance/Shot2Story#14]
In [90k_gptv_train.json](https://huggingface.co/datasets/mhan/shot2story/blob/main/90k_gptv_train.json), I found that all texts in "audio_captions" is "Placeholder for audio caption.", and all texts in "captions" is "Placeholder for visual caption.". The same problem exists with the corresponding part of data in [134k_full_train.json](https://huggingface.co/datasets/mhan/shot2story/blob/main/134k_full_train.json).
![image](https://github.com/user-attachments/assets/c4bc04a4-be7e-4b19-b4ce-f8d00d3d4e39)

I believe this is a serious bug and hope you can fix it soon.

**Comment by yellow-binary-tree** [comment]
Oh I found at https://github.com/bytedance/Shot2Story/issues/7 that for GPTV generated video summary, per-shot captions are not provided.

**Comment by youthHan** [comment]
Hi I see you close this issue. I put the corresponding explanation here for feeding others: the 90K version is purely from GPTV, and no manual annotations So the per-shot captions (either visual or audio) are empty and marked as placeholder for easy processing in codes.
