### ISSUE TITLE
 No matching distribution found for byted-dataloader==0.3.6failed

### ISSUE THREAD

**Issue by websieu** [bytedance/Shot2Story#3]
Hi, when I run###  **conda env create -f conda_env.yml** on Google Colab, I encounter an error:

_Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement byted-dataloader==0.3.6 (from versions: none)
ERROR: No matching distribution found for byted-dataloader==0.3.6_

I tried to search for **byted-dataloader** on PyPI but found no package named byted-dataloader.

is this package private or I did something wrong on google colab?

many thanks

**Comment by youthHan** [comment]
Hi, please pull the latest update and try to shift to *temp* branch and see if it works.

**Comment by youthHan** [comment]
Hi I will close this issue due to inactivity. Thanks.
