### ISSUE TITLE
Error when run  python data/scripts/process_videos.py

### ISSUE THREAD

**Issue by jpWang** [bytedance/Shot2Story#6]
Hi, thanks for this great work~
When running python data/scripts/process_videos.py, I get the following error:
![image](https://github.com/bytedance/Shot2Story/assets/52776462/7b70766f-f831-4bf7-992d-e55c2547c8b9)
I use the data shared in https://github.com/bytedance/Shot2Story/issues/5. And I do not know why this happened. 
Looking forward to your reply~ Thanks again.

**Comment by youthHan** [comment]
It seems corruption is caused by the video. 
![image](https://github.com/bytedance/Shot2Story/assets/18671115/88c773d5-4bdf-4ce2-aa87-869492b31360)

Can you please check
1. if the already processed video shots are good,
2. which clip id(s) cause this corruption?

**Comment by jpWang** [comment]
Thanks for your really quick reply, and sorry for this stupid issue... The videos in https://github.com/bytedance/Shot2Story/issues/5 are already processed. Very nice sharing.
